version: 1.0.{build}
skip_tags: true
os: Visual Studio 2015
configuration:
- Debug
- Release
before_build:
- cmd: >-
    git submodule update --init

    appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

    restore.cmd
build:
  project: CanvasDiagram.sln
  verbosity: minimal